### PR TITLE
update meta-on-semiconductor branch to 2020.1

### PR DESCRIPTION
**Pull request by frebaudo-witekio**

### CODE REVIEW

**Comment by narrucmot** [comment]
Shouldn't this be 2020.2 branch to match meta-avnet, petalinux, and hdl?

**Comment by frebaudo-witekio** [comment]
No. I created a new branch 2020.1 on the meta-on-semiconductor which contains the BSP features of the dual-camera mezzanine for Petalinux 2020.1. This PR will be merged in Petalinux 2020.1 branch thus it needs to be 2020.1.
"frebaudo-witekio wants to merge 1 commit into 2020.1 from frebaudo/dev_2020.1"

**Comment by narrucmot** [comment]
I guess what I was asking was this script variable is set to 2020.2 like the script variable for the meta-avnet branch is set to 2020.2, right?

--Tom
________________________________

**Review by AlbertaBeef — APPROVED** [review]

**Comment by frebaudo-witekio** [comment]
Here for Petalinux 2020.1 I want to build the 2020.1 version of the meta-avnet so I set the branch to 2020.1. If you look at `scripts/common.sh` META_AVNET_BRANCH is set to 2020.1 in Petalinux 2020.1
________________________________

**Pull request merged**
